In [27]:
## Binomial distribution

from scipy.stats import binom
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import numpy as np

# we generate random variable sample by providing the parameters n and p
x = binom.rvs(20, 0.7, size=100)

In [2]:
probs = binom.pmf(x, 20, 0.7)
probs

array([0.07160367, 0.11439674, 0.19163898, 0.17886305, 0.11439674,
       0.17886305, 0.19163898, 0.11439674, 0.19163898, 0.16426199,
       0.17886305, 0.17886305, 0.19163898, 0.11439674, 0.13042097,
       0.16426199, 0.17886305, 0.17886305, 0.06536957, 0.17886305,
       0.17886305, 0.13042097, 0.13042097, 0.07160367, 0.17886305,
       0.17886305, 0.13042097, 0.07160367, 0.03081708, 0.16426199,
       0.19163898, 0.17886305, 0.19163898, 0.17886305, 0.13042097,
       0.19163898, 0.06536957, 0.13042097, 0.17886305, 0.11439674,
       0.06536957, 0.17886305, 0.16426199, 0.17886305, 0.06536957,
       0.19163898, 0.16426199, 0.19163898, 0.16426199, 0.17886305,
       0.06536957, 0.19163898, 0.11439674, 0.07160367, 0.16426199,
       0.06536957, 0.16426199, 0.11439674, 0.19163898, 0.13042097,
       0.11439674, 0.00683934, 0.13042097, 0.11439674, 0.02784587,
       0.19163898, 0.00683934, 0.03081708, 0.06536957, 0.17886305,
       0.17886305, 0.16426199, 0.17886305, 0.19163898, 0.17886

In [28]:

# now we'll plot it
plt.stem(x, probs, use_line_collection=True)
plt.show

TypeError: stem() got an unexpected keyword argument 'use_line_collection'

In [18]:


# we can get the probabilities of all values of x
x = np.array([0,1,2,3,4,5,6,7,8,9,10])
prob = binom.pmf(x, 10, 0.5)
prob

array([0.00097656, 0.00976563, 0.04394531, 0.1171875 , 0.20507812,
       0.24609375, 0.20507812, 0.1171875 , 0.04394531, 0.00976563,
       0.00097656])

In [19]:
# sum of prob of 7 to 10
sum(prob[7:])

0.17187500000000003

In [20]:
# by using cdf method
binom.cdf(10, 10,0.5) - binom.cdf(6,10,0.5)

0.171875

In [22]:
### Poisson distribution

from scipy.stats import poisson

# generate random variable samples using poisson distribution
x = poisson.rvs(mu = 3, size = 100)
x

array([2, 5, 1, 4, 4, 4, 3, 1, 1, 1, 2, 4, 1, 3, 1, 4, 1, 4, 3, 5, 1, 3,
       3, 5, 4, 4, 3, 3, 2, 5, 2, 3, 4, 3, 2, 4, 3, 4, 2, 1, 4, 9, 4, 0,
       2, 3, 3, 3, 2, 2, 3, 1, 4, 2, 2, 5, 2, 0, 6, 5, 5, 4, 1, 1, 7, 1,
       2, 2, 2, 5, 0, 1, 3, 3, 3, 3, 3, 2, 4, 2, 1, 5, 4, 3, 6, 2, 4, 1,
       1, 2, 1, 1, 5, 7, 1, 4, 3, 7, 1, 2], dtype=int64)

In [25]:
prob = poisson.pmf(x, mu=3)
prob

array([0.22404181, 0.10081881, 0.14936121, 0.16803136, 0.16803136,
       0.16803136, 0.22404181, 0.14936121, 0.14936121, 0.14936121,
       0.22404181, 0.16803136, 0.14936121, 0.22404181, 0.14936121,
       0.16803136, 0.14936121, 0.16803136, 0.22404181, 0.10081881,
       0.14936121, 0.22404181, 0.22404181, 0.10081881, 0.16803136,
       0.16803136, 0.22404181, 0.22404181, 0.22404181, 0.10081881,
       0.22404181, 0.22404181, 0.16803136, 0.22404181, 0.22404181,
       0.16803136, 0.22404181, 0.16803136, 0.22404181, 0.14936121,
       0.16803136, 0.0027005 , 0.16803136, 0.04978707, 0.22404181,
       0.22404181, 0.22404181, 0.22404181, 0.22404181, 0.22404181,
       0.22404181, 0.14936121, 0.16803136, 0.22404181, 0.22404181,
       0.10081881, 0.22404181, 0.04978707, 0.05040941, 0.10081881,
       0.10081881, 0.16803136, 0.14936121, 0.14936121, 0.02160403,
       0.14936121, 0.22404181, 0.22404181, 0.22404181, 0.10081881,
       0.04978707, 0.14936121, 0.22404181, 0.22404181, 0.22404

In [32]:
matplotlib.pyplot.stem(x, prob, use_line_collection=True)

NameError: name 'matplotlib' is not defined

TypeError: stem() got an unexpected keyword argument 'use_line_collection'